# Based on:
# https://github.com/joerick/cibuildwheel/blob/master/examples/github-deploy.yml

name: "Kits"

on:
  push:
    branches:
      # Don't build kits all the time, but do if the branch is about kits.
      - "**/*kit*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  wheels:
    name: "Build wheels on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2

      - name: "Install Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: "Install requirements"
        run: |
          python -m pip install numpy cibuildwheel

      - name: "Build wheels"
        env:
          CIBW_BUILD: cp39*
          CIBW_BEFORE_BUILD: python -m pip install numpy
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          ls -al wheelhouse/

      - name: "Upload wheels"
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: wheelhouse/*.whl

  sdist:
    name: "Build source distribution"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2

      - name: "Install Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: "Install requirements"
        run: |
          python -m pip install numpy

      - name: "Build sdist"
        run: |
          python setup.py sdist
          ls -al dist/

      - name: "Upload sdist"
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.tar.gz
